### ISSUE TITLE
Basic praise function

### ISSUE THREAD

**Issue by gaborcsardi** [gaborcsardi/praise#1]
So I thought for starters we could have something like: 

```r
praise <- function(template = "This is ${superb}!") {
  ## ...
}
```

and then `praise` just inserts a random adjective from `superb` into the template. 

?

**Comment by Ironholds** [comment]
Sounds good! We could also import your package building package and have praise_build() which simply calls that with a piece of praise if it succeeds.

**Comment by gaborcsardi** [comment]
I guess I will import `praise` in `mason`, or maybe that's what you meant. I think `praise` could be pretty generic, the madlibs engine if you like.

**Comment by Ironholds** [comment]
Ahh, that'd make more sense!

**Comment by hadley** [comment]
I think it would be good to break the word list down in to parts of speech so you could have "You're a {adverb} programmer" or "{Adjective} work!".  (and matching capitalisation would also be handy)

**Comment by gaborcsardi** [comment]
@hadley yes, that makes sense. I would even classify them further. "{Adjective} work!" often makes less sense than "{Positive adjective} work!".

Matching capitalization is also a good idea.

**Comment by hadley** [comment]
I just assumed all the adjectives would be positive in this package ;)

**Comment by gaborcsardi** [comment]
Yeah, right. :)
